<?php

/**
 * Prepares variables for Views iCal template.
 *
 * Default template: views-view-ical.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - view: A View object.
 */
function views_ical_preprocess_views_view_ical(&$variables) {
  module_load_include('inc', 'views', 'views.theme');
  
  $view = $variables['view'];
  if ($view->display_handler->getOption('sitename_title')) {
    $title = $config->get('name');
    if ($slogan = $config->get('slogan')) {
      $title .= ' - ' . $slogan;
    }
  }
  else {
    $title = $view->getTitle();
  }
  $variables['title'] = $title;
  
  template_preprocess_views_view_unformatted($variables);
}

/**
 * Prepares variables for Views iCal Fields template.
 *
 * Default template: views-view-ical-fields.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - view: A View object.
 */
function views_ical_preprocess_views_view_ical_fields(&$variables) {
  module_load_include('inc', 'views', 'views.theme');
  template_preprocess_views_view_fields($variables);
}